# Generated by Django 3.2.25 on 2025-05-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_movies_tollywood'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollywood',
            name='trailer',
            field=models.URLField(default=True, max_length=500),
        ),
    ]
