# Generated by Django 3.2.25 on 2025-05-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_tollywood_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tollywood',
            name='producer',
        ),
        migrations.AddField(
            model_name='tollywood',
            name='actress',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
