# Generated by Django 3.2.25 on 2025-05-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20250523_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tollywood',
            old_name='actress',
            new_name='Actress',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='collections',
            new_name='Collections',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='date_of_release',
            new_name='Date_of_release',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='director',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='images',
            new_name='Images',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='movie_name',
            new_name='Movie_name',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='rating',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='trailer',
            new_name='Trailer',
        ),
    ]
