# Generated by Django 3.2.25 on 2025-05-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20250523_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tollywood',
            old_name='Actress',
            new_name='actress',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='Collections',
            new_name='collections',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='Date_of_release',
            new_name='date_of_release',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='Director',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='Images',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='Movie_name',
            new_name='movie_name',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='tollywood',
            old_name='Trailer',
            new_name='trailer',
        ),
    ]
